repo_name: polars-quant
repo_url: https://github.com/Firstastor/polars-quant/
site_author: Firstastor
site_name: Polars-Quant
site_url: https://firstastor.github.io/polars-quant/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Firstastor

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - 开始:
      - index.md
      - 特性: start/features.md
      - 安装: start/installation.md
      - 使用: start/usage.md
  - API: api.md

plugins:
  - search

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
